library(checkmate)


# `example_ps` is generated by the package itself so the getters' fixture can
# never drift from what ps1_create_bulk_users() actually emits (Microsoft Graph
# syntax). All identities are deliberately fake.
local({
  fixture_dir <- tempfile("ubep-fixture-")
  dir.create(fixture_dir)
  readr::write_csv(
    data.frame(
      Nome = c("Pinco", "Ciccio"),
      Cognome = c("Pallino", "Pasticcio"),
      Email = c("pinco.pallino@example.org", "ciccio.pasticcio@example.org"),
      Prj1_ID = c(1, 2),
      Prj1_role = c("user", "power"),
      Prj1_DAG = c("a", "b"),
      Prj2_ID = c(NA, NA),
      Prj2_role = c(NA, NA),
      Prj2_DAG = c(NA, NA)
    ),
    file.path(fixture_dir, "fixture.csv"),
    na = ""
  )
  ps1_create_bulk_users("fixture", fixture_dir, "fixture-only-value")
  example_ps <<- readr::read_lines(file.path(fixture_dir, "fixture.ps1"))
})


example_tbl <- data.frame(
  Nome = c("Pinco", "Ciccio", "Mario", "", NA),
  Cognome = c("Pallino", "Pasticcio", "Rossi", "", NA),
  Email = c(
    "pinco.pallino.1@fobar.org", "ciccio.past@barfoo.com",
    "mr@example.boh", "", NA
  ),
  Prj1_ID = c(1, 2, NA, NA, NA),
  Prj1_role = c("user", "power", NA, "", NA),
  Prj1_DAG = c("a", "b", NA, "", NA),
  Prj2_ID = c(3, NA, 4, NA, NA),
  Prj2_role = c("user", NA, "boss", "", NA),
  Prj2_DAG = c("c", NA, "d", "", NA)
)
